-- 1. CRIA A TABELA SERVIDOR 
CREATE TABLE TESTEFACULDADE.SERVIDOR (ID INT PRIMARY KEY, NOME VARCHAR(50), META INT)
-- 2. CRIA A TABELA DE SEXO
CREATE TABLE TESTEFACULDADE.SEXO (ID INT PRIMARY KEY, SEXO VARCHAR(20))
-- 3. CRIA A TABELA DE PESSOA JÁ COM A CONSTRAINT PARA VERIFICAR SE A IDADE É MAIOR OU IGUAL A 16
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.PESSOA (
	ID INT PRIMARY KEY,
	NOME VARCHAR(50),
	ID_SEXO INT REFERENCES TESTEFACULDADE.SEXO (ID),
	CPF NUMERIC(11) NOT NULL,
	TELEFONE NUMERIC(20),
	EMAIL VARCHAR(200),
	DATA_NASCIMENTO DATE NOT NULL,
	ID_SERVIDOR INT REFERENCES TESTEFACULDADE.SERVIDOR (ID),
	CONSTRAINT CHK_IDADE_MINIMA CHECK (EXTRACT(YEAR FROM AGE (CURRENT_DATE, DATA_NASCIMENTO)) >= 16)
)
-- 4. CRIA A TABELA DE ATENDENTES
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.ATENDENTES(
	ID INT PRIMARY KEY,
	ID_PESSOA INT REFERENCES TESTEFACULDADE.PESSOA(ID),
	CARGO VARCHAR(100),
	DATA_INICIO DATE,
	DATA_FIM DATE
)
-- 5. CRIA A TABELA DE STATUS
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.STATUS(
	ID INT PRIMARY KEY,
	DESCRICAO VARCHAR(20)
)
-- 6. CRIA A TABELA DE PRIORIDADE
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.PRIORIDADE(
	ID INT PRIMARY KEY,
	DESCRICAO VARCHAR(20)
)
-- 7. CRIA A TABELA DE ATENDIMENTO
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.ATENDIMENTO(
	ID INT PRIMARY KEY,
	ID_PESSOA INT REFERENCES TESTEFACULDADE.PESSOA (ID),
	ID_ATENDETENTE INT  REFERENCES TESTEFACULDADE.ATENDENTES (ID),
	ID_STATUS INT  REFERENCES TESTEFACULDADE.STATUS (ID),
	ID_PRIORIDADE INT  REFERENCES TESTEFACULDADE.PRIORIDADE (ID),
	DATA_CHEGADA DATE,
	DATA_INICIO DATE,
	DATA_FIM DATE
)
-- 8. CRIA A TABELA DE AVALIACAO
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.AVALIACAO(
	ID INT PRIMARY KEY,
	ID_ATENDIMENTO INT REFERENCES TESTEFACULDADE.ATENDIMENTO(ID),
	NOTA INT,
	OBSERVACOES VARCHAR(1000)
)
-- 9. CRIA A TABELA DE PREMIO
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.PREMIO(
	ID INT PRIMARY KEY,
	PREMIO VARCHAR(100)
)
-- 10. CRIA A TABELA DE METAS BATIDAS
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.METAS_BATIDAS(
	ID INT PRIMARY KEY,
	META_BATIDA VARCHAR (200),
	DATA_BATIDA DATE,
	ID_PREMIO INT REFERENCES TESTEFACULDADE.PREMIO(ID),
	ID_ATENDENTE INT REFERENCES TESTEFACULDADE.ATENDENTES(ID)
)
-- 1.. CRIA A TABELA DA LOJA
CREATE TABLE IF NOT EXISTS TESTEFACULDADE.LOJA(
	id INT PRIMARY KEY,
	ID_PREMIO INT REFERENCES TESTEFACULDADE.PREMIO(ID),
	PRECO_RECOMPENSA FLOAT,
	QUANTIDADE INT,
	ID_ATENDENTE INT REFERENCES TESTEFACULDADE.ATENDENTES(ID),
	DATA_RETIRADA DATE,
	DATA_ADICAO DATE
)
